name: daily-status
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest

      - name: Run all scraper tests and save status
        run: python generate_schools_status.py

      - name: Commit status.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/status.json
          git commit -m "ci: update daily status" || echo "No changes to commit"
          git push
