name: release
on:
  release:
    types:
      - published

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set version to today's date (YYYY.M.D)
        run: |
          today=$(date +"%Y.%-m.%-d")
          sed -i "s/^version\s*=\s*\".*\"/version = \"$today\"/" pyproject.toml

      - name: Commit version bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore: bump version to $today" || echo "No changes to commit"
          git push

  pypi-publish:
    runs-on: ubuntu-latest

    environment: pypi

    permissions:
      id-token: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
